package de.dhbw.tinf11b2.ofk.view;

import java.util.ArrayList;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import de.dhbw.tinf11b2.ofk.presenter.OFKViewListener;

public class RegisterSeite extends CustomComponent implements ClickListener, OFKView {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	List<OFKViewListener> listeners = new ArrayList<OFKViewListener>();	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button speicherButton;
	@AutoGenerated
	private TextField emailFeld;
	@AutoGenerated
	private PasswordField bestaetigungsFeld;
	@AutoGenerated
	private PasswordField kennwortFeld;
	@AutoGenerated
	private TextField namenFeld;
	
	private Button zurueckButton;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RegisterSeite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");
		
		// zurueckButton
				zurueckButton = new Button("Zurück",this);
				zurueckButton.setImmediate(true);
				zurueckButton.setWidth("-1px");
				zurueckButton.setHeight("-1px");
				mainLayout.addComponent(zurueckButton, "top:92.0%;left:90.0%;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("90.0%");
		verticalLayout_1.setMargin(false);
		
		// namenFeld
		namenFeld = new TextField();
		namenFeld.setCaption("Bitte Nutzername eingeben:");
		namenFeld.setImmediate(false);
		namenFeld.setWidth("-1px");
		namenFeld.setHeight("-1px");
		verticalLayout_1.addComponent(namenFeld);
		verticalLayout_1.setComponentAlignment(namenFeld, new Alignment(24));
		
		// kennwortFeld
		kennwortFeld = new PasswordField();
		kennwortFeld.setCaption("Bitte Wunschkennwort eingeben:");
		kennwortFeld.setImmediate(false);
		kennwortFeld.setWidth("-1px");
		kennwortFeld.setHeight("-1px");
		verticalLayout_1.addComponent(kennwortFeld);
		verticalLayout_1.setComponentAlignment(kennwortFeld, new Alignment(48));
		
		// bestaetigungsFeld
		bestaetigungsFeld = new PasswordField();
		bestaetigungsFeld.setCaption("Kennwort bestätigen:");
		bestaetigungsFeld.setImmediate(false);
		bestaetigungsFeld.setWidth("-1px");
		bestaetigungsFeld.setHeight("-1px");
		verticalLayout_1.addComponent(bestaetigungsFeld);
		verticalLayout_1.setComponentAlignment(bestaetigungsFeld,
				new Alignment(20));
		
		// emailFeld
		emailFeld = new TextField();
		emailFeld.setCaption("Bitte Emailadresse eingeben:");
		emailFeld.setImmediate(false);
		emailFeld.setWidth("-1px");
		emailFeld.setHeight("-1px");
		verticalLayout_1.addComponent(emailFeld);
		verticalLayout_1.setComponentAlignment(emailFeld, new Alignment(48));
		
		// speicherButton
		speicherButton = new Button();
		speicherButton.setCaption("Speichern");
		speicherButton.setImmediate(false);
		speicherButton.setWidth("-1px");
		speicherButton.setHeight("-1px");
		verticalLayout_1.addComponent(speicherButton);
		verticalLayout_1.setComponentAlignment(speicherButton,
				new Alignment(10));
		
		return verticalLayout_1;
	}

	public void addListener(OFKViewListener listener) {
		listeners.add(listener);
		
	}


	public void buttonClick(ClickEvent event) {
		 for (OFKViewListener listener: listeners)
	            listener.buttonClick(event.getButton()
	                                 .getCaption());
		
	}
	
}
